<?php

namespace AppBundle\Repository;

/**
 * CommandeMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
