<?php

namespace AppBundle\Repository;

/**
 * PointRelaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointRelaisRepository extends \Doctrine\ORM\EntityRepository
{
}
