# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.geocoder_service:
        class: AppBundle\Service\GeocodeService
        autowire: true

    app.doctrine.produit_affichage_client:
        class: AppBundle\Listener\ProduitSelectListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    app.doctrine.produit:
        class: AppBundle\Listener\ProduitListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    app.doctrine.livraison:
        class: AppBundle\Listener\LivraisonListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber, connection: default }